/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.Ticket;
import javax.swing.JOptionPane;

/**
 *
 * @author alejo
 */
public class crearTicket extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(crearTicket.class.getName());
    
     private Cliente cliente; // cliente logueado
    /**
     * Creates new form crearTicket
     */
    public crearTicket() {
        this.cliente = cliente; 
        initComponents();
        setTitle("Crear nuevo ticket");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCrearTicket = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTicketCorreoElectronico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        comboPrioridad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTicketNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgCrearTicket.setBackground(new java.awt.Color(255, 255, 255));
        bgCrearTicket.setForeground(new java.awt.Color(0, 0, 0));
        bgCrearTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bgCrearTicket.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        jPanel2.setBackground(new java.awt.Color(26, 67, 191));

        jLabel1.setBackground(new java.awt.Color(26, 67, 191));
        jLabel1.setFont(new java.awt.Font("Inter 24pt Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crea una solicitud");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bgCrearTicket.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 610, 80));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        bgCrearTicket.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, -1));

        txtTitulo.setBackground(new java.awt.Color(255, 255, 255));
        txtTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        bgCrearTicket.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 310, 30));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correo electronico");
        bgCrearTicket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, -1));

        txtTicketCorreoElectronico.setBackground(new java.awt.Color(255, 255, 255));
        txtTicketCorreoElectronico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        bgCrearTicket.add(txtTicketCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 310, 30));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Prioridad");
        bgCrearTicket.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 190, -1));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jScrollPane1.setViewportView(txtDescripcion);

        bgCrearTicket.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 310, 100));

        comboPrioridad.setBackground(new java.awt.Color(255, 255, 255));
        comboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Alta", "Media", "Baja" }));
        comboPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrioridadActionPerformed(evt);
            }
        });
        bgCrearTicket.add(comboPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 120, 30));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Descripción del problema");
        bgCrearTicket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, -1));

        jButton1.setBackground(new java.awt.Color(20, 74, 117));
        jButton1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar solicitud");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bgCrearTicket.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 310, 40));

        txtTicketNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtTicketNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        bgCrearTicket.add(txtTicketNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgCrearTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgCrearTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPrioridadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre = txtTicketNombre.getText();
        String correoElectronico = txtTicketCorreoElectronico.getText();
        String titulo = txtTitulo.getText();
        String descripcion = txtDescripcion.getText();
        String prioridad = comboPrioridad.getSelectedItem().toString();
        
        // 2. Validar datos (opcional)
        if (titulo.isEmpty() || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
        return;      
    }//GEN-LAST:event_jButton1ActionPerformed
        
     //Crear objeto Ticket
    Ticket nuevoTicket = new Ticket();
    nuevoTicket.setTitulo(titulo);
    nuevoTicket.setDescripcion(descripcion);
    nuevoTicket.setPrioridad(prioridad);
    nuevoTicket.setEstado("Abierto");
    nuevoTicket.setClienteId(cliente.getId()); // cliente logueado
    nuevoTicket.setClienteNombre(cliente.getNombre());
    nuevoTicket.setClienteEmail(cliente.getClienteEmail());
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgCrearTicket;
    private javax.swing.JComboBox<String> comboPrioridad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTicketCorreoElectronico;
    private javax.swing.JTextField txtTicketNombre;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
