/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author alejo
 */
public class panelControlAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(panelControlAdmin.class.getName());

    /**
     * Creates new form panelControlAdmin
     */
    public panelControlAdmin() {
        
        try {
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        SwingUtilities.updateComponentTreeUI(this); // Refresca el aspecto visual del panel
        } catch (Exception e) {
        e.printStackTrace();
}
        initComponents();
        
        btnAdministrarTickets.setBackground(new Color(0, 153, 255));
        btnAdministrarTickets.setForeground(Color.WHITE);
        btnAdministrarTickets.setOpaque(true);
        btnAdministrarTickets.setBorderPainted(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgrounPanelAdmin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnVerTicketsCerrados = new javax.swing.JButton();
        btnAdministrarTickets = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgrounPanelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        backgrounPanelAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 67, 191));

        jLabel1.setBackground(new java.awt.Color(26, 67, 191));
        jLabel1.setFont(new java.awt.Font("Inter 24pt Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Que deseas hacer hoy?");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\alejo\\Downloads\\buildings (4).png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 67, 191));
        jLabel4.setText("HelpDesk Lite");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\alejo\\Downloads\\user.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\alejo\\Downloads\\home.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backgrounPanelAdmin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 110));

        btnVerTicketsCerrados.setBackground(new java.awt.Color(20, 74, 117));
        btnVerTicketsCerrados.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        btnVerTicketsCerrados.setForeground(new java.awt.Color(255, 255, 255));
        btnVerTicketsCerrados.setText("     Ver tickets cerrados");
        btnVerTicketsCerrados.setBorder(null);
        btnVerTicketsCerrados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVerTicketsCerrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTicketsCerradosActionPerformed(evt);
            }
        });
        backgrounPanelAdmin.add(btnVerTicketsCerrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 270, 50));

        btnAdministrarTickets.setBackground(new java.awt.Color(20, 74, 117));
        btnAdministrarTickets.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        btnAdministrarTickets.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrarTickets.setText("     Administrar Tickets");
        btnAdministrarTickets.setBorder(null);
        btnAdministrarTickets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministrarTickets.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdministrarTickets.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdministrarTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarTicketsActionPerformed(evt);
            }
        });
        backgrounPanelAdmin.add(btnAdministrarTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrounPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgrounPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarTicketsActionPerformed
        // TODO add your handling code here:
        
        AdministrarTicketsAdmin mainAdministrarTicketsAdmin = new AdministrarTicketsAdmin();
        mainAdministrarTicketsAdmin.setVisible(true);
        mainAdministrarTicketsAdmin.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAdministrarTicketsActionPerformed

    private void btnVerTicketsCerradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTicketsCerradosActionPerformed
        // TODO add your handling code here:
        VerTicketsCerradosAdmin mainTicketsCerradosAdmin = new VerTicketsCerradosAdmin();
        mainTicketsCerradosAdmin.setVisible(true);
        mainTicketsCerradosAdmin.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnVerTicketsCerradosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgrounPanelAdmin;
    private javax.swing.JButton btnAdministrarTickets;
    private javax.swing.JButton btnVerTicketsCerrados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
